@API_HostAddress = http://localhost:5000

GET {{API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{API_HostAddress}}/api/products/
Accept: application/json

###

@ProductId = 2
GET {{API_HostAddress}}/api/products/{{ProductId}}
Accept: application/json

###

// 404
GET  {{API_HostAddress}}/api/Buggy/not-found/
Accept: application/json

###

// 400
GET  {{API_HostAddress}}/api/Buggy/bad-request/
Accept: application/json

###

// 401
GET  {{API_HostAddress}}/api/Buggy/unauthorized/
Accept: application/json

###

// 400
GET  {{API_HostAddress}}/api/Buggy/validation-error/
Accept: application/json

###

// 500
GET  {{API_HostAddress}}/api/Buggy/server-error/
Accept: application/json

###

GET {{API_HostAddress}}/api/Basket/
Cookie: buyerId=2ffde21a-7a83-46c5-96d7-2140cba4b4cf
Accept: application/json

###

@productId = 3
@quantity = 3

POST {{API_HostAddress}}/api/Basket?productId={{productId}}&quantity={{quantity}}
Cookie: buyerId=2ffde21a-7a83-46c5-96d7-2140cba4b4cf
Accept: application/json

###£z

DELETE {{API_HostAddress}}/api/Basket?productId={{productId}}&quantity={{quantity}}
Cookie: buyerId=2ffde21a-7a83-46c5-96d7-2140cba4b4cf
Accept: application/json

###
